TRUNCATE  folders, notes RESTART IDENTITY CASCADE;

INSERT INTO folders (name)
VALUES
  ('Important'),
  ('Super'),
  ('Spangley');

INSERT INTO notes (name, modified, folder_id, content)
VALUES
    ('Dogs', '2019-01-03T00:00:00.000Z', 1, 'Magni omnis pariatur sit distinctio est ullam. Laboriosam fugiat quia nobis fuga. Est atque sit eligendi qui animi illo officia.\n \rDolore nobis nam repudiandae est excepturi. Excepturi perspiciatis a voluptatibus autem minima. Qui placeat error impedit qui.\n \rNostrum nemo sint. Necessitatibus et molestiae est ullam doloribus. Quia rerum molestias odio dolorem maiores ea non autem quidem. Necessitatibus non voluptas sint mollitia. Enim eos nihil.'),
    ('Cats', '2018-08-15T23:00:00.000Z', 1, 'Debitis et assumenda. Sint qui iure fugit dolor. Perferendis voluptas voluptatum ut. Placeat pariatur dolorum temporibus consequatur dolores soluta fuga.\n \rConsectetur numquam sit repellat laborum tempora quisquam. Et corrupti necessitatibus at rerum eum molestiae. Asperiores nihil sequi voluptatem. Aperiam fuga tenetur dicta voluptatem. Vel quia dolores laborum non repudiandae non ut vel. Incidunt nostrum amet aperiam repudiandae et alias quam.\n \rMaxime explicabo in. Totam dolorem modi explicabo qui necessitatibus quod voluptas accusantium. Repellat quis libero commodi. Sed aut ea porro saepe dolores eligendi officia.'),
    ('Pigs', '2018-03-01T00:00:00.000Z', 1, 'Soluta incidunt enim quod eveniet modi molestiae. Alias quia expedita aspernatur. Labore et saepe ea praesentium voluptatem. Voluptatem illum non accusantium sint cum debitis. Quis incidunt itaque sit quia illo rerum. Consequuntur quam quo vel rerum quis voluptate expedita.\n \rAdipisci eaque molestiae quos. Cupiditate rerum modi dicta enim quisquam qui minima. Est quae sed non tenetur excepturi dolorem ratione perferendis et.\n \rEum ullam modi aliquam laboriosam nesciunt. Itaque cumque aut et magnam laboriosam. Et possimus in rerum soluta ratione vero. Amet omnis quae consequatur eos provident fuga ut. Voluptatibus nobis vero.'),
    ('Birds', '2019-01-04T00:00:00.000Z', 2, 'Vitae reprehenderit fugit sed voluptatem. Harum eum sed qui at. Ex ut ducimus voluptatem voluptates dignissimos.\n \rAut hic dolore non accusantium. Sunt voluptates mollitia eum odit animi itaque officiis. Eveniet voluptatum numquam esse. Et qui architecto rerum nam et.\n \rOccaecati unde qui qui unde ut mollitia sunt. Tempore labore nemo. Aliquam exercitationem consequatur ducimus velit dolorum eaque voluptatum. Ex illum culpa animi a odio. Dolore et iste ab dolores. Autem nobis et totam ad velit qui.'),
    ('Bears', '2018-07-12T23:00:00.000Z', 2, 'Iste pariatur ea cupiditate a officiis culpa. Tenetur aspernatur voluptatum voluptatum dolores numquam. Amet commodi ut alias id sint recusandae sed praesentium. Dolores aut nihil laudantium qui voluptas beatae accusantium.\n \rQuas asperiores optio dolore aut quod eaque eaque sunt. Ut non ut sed at voluptas dolorum repellat quasi. Pariatur facilis dignissimos dolorem qui fugiat sed molestias porro deserunt. Molestiae et nam natus excepturi voluptatum. Fugit est velit aut qui quae perspiciatis dolores aut. Nulla eaque facilis ut consequatur enim veniam eaque eum.\n \rQui architecto perferendis qui corporis tempore a fuga necessitatibus. Dolorem et ut in provident. Sit itaque non et quia. Libero quo impedit aut qui ratione voluptas consequuntur adipisci. Ut vel molestias.'),
    ('Horses', '2018-08-20T23:00:00.000Z', 3, 'Temporibus magni sint temporibus qui quam modi. Reiciendis et quidem dolorem sunt ipsum sint doloribus qui ipsam. Necessitatibus similique architecto error nostrum veritatis repellendus. Pariatur vel sequi magnam quia aut et placeat. Quo soluta atque velit voluptatibus et voluptatem reprehenderit.\n \rLibero ipsa voluptatum consequatur explicabo aliquid nihil unde. Rerum sint iusto placeat dolores temporibus rem molestiae veniam. Eaque non consequatur voluptatem occaecati. Aut quia in temporibus. Recusandae quo veniam est et sint vitae atque eveniet dolorum. Possimus nihil expedita rerum consequatur dolores quod vel.\n \rSit eum quia et et voluptatem placeat. Est quis qui unde. Reiciendis aut laudantium et officia eos tempora. Ducimus repellendus quasi velit velit ad sed velit. At est dolores expedita voluptates repudiandae in.');